# Generated by Django 3.2.19 on 2023-08-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_rename_user_id_diary_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
